#!/bin/bash

# Wedding Invitation Link Generator
# Generates personalized links and WhatsApp messages for guests

# CHANGE THIS TO YOUR ACTUAL WEBSITE URL
WEBSITE_URL="https://mohamed-mariam-wedding-six.vercel.app"

# Country code for all guests (Egypt)
COUNTRY_CODE="20"

# File paths
GUEST_LIST="guest-list.txt"
GENERATED_LINKS="generated-links.txt"
OUTPUT_FILE="whatsapp-messages.txt"

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Create generated-links.txt if it doesn't exist
if [ ! -f "$GENERATED_LINKS" ]; then
    echo "# Generated invitation links" > "$GENERATED_LINKS"
    echo "# Format: Name | Phone | Link | Generated Date" >> "$GENERATED_LINKS"
    echo "# DO NOT EDIT THIS FILE MANUALLY - Use generate-links.sh script" >> "$GENERATED_LINKS"
    echo "" >> "$GENERATED_LINKS"
fi

# Create output file
echo "====================================" > "$OUTPUT_FILE"
echo "WEDDING INVITATION WHATSAPP MESSAGES" >> "$OUTPUT_FILE"
echo "Generated: $(date)" >> "$OUTPUT_FILE"
echo "====================================" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

echo -e "${BLUE}Wedding Invitation Link Generator${NC}"
echo "===================================="
echo ""

# Counter for new links
NEW_COUNT=0
EXISTING_COUNT=0

# Read guest list
while IFS=, read -r name phone; do
    # Trim whitespace
    name=$(echo "$name" | xargs)
    phone=$(echo "$phone" | xargs)
    
    # Remove any + or leading zeros, then add country code
    phone=$(echo "$phone" | sed 's/^+//' | sed 's/^0//')
    phone="+${COUNTRY_CODE}${phone}"
    
    # Skip empty lines
    if [ -z "$name" ]; then
        continue
    fi
    
    # Check if already generated
    if grep -q "$name|$phone|" "$GENERATED_LINKS"; then
        echo -e "${YELLOW}⏭  Skipping $name (already generated)${NC}"
        EXISTING_COUNT=$((EXISTING_COUNT + 1))
        continue
    fi
    
    # URL encode name (replace spaces with +)
    encoded_name=$(echo "$name" | sed 's/ /+/g')
    
    # Generate personalized link
    invitation_link="${WEBSITE_URL}/?to=${encoded_name}"
    
    # Generate WhatsApp message
    message="Dear ${name},%0A%0AWe would love to have you celebrate our special day with us!%0A%0A${invitation_link}%0A%0AMohamed & Mariam"
    
    # WhatsApp link
    whatsapp_link="https://wa.me/${phone}?text=${message}"
    
    # Save to generated-links.txt
    echo "${name} | ${phone} | ${invitation_link} | $(date)" >> "$GENERATED_LINKS"
    
    # Output to file
    echo "====================================" >> "$OUTPUT_FILE"
    echo "Guest: $name" >> "$OUTPUT_FILE"
    echo "Phone: $phone" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
    echo "Personalized Link:" >> "$OUTPUT_FILE"
    echo "$invitation_link" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
    echo "WhatsApp Link (click to send):" >> "$OUTPUT_FILE"
    echo "$whatsapp_link" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
    
    echo -e "${GREEN}✓ Generated link for: $name${NC}"
    NEW_COUNT=$((NEW_COUNT + 1))
    
done < "$GUEST_LIST"

echo ""
echo "===================================="
echo -e "${GREEN}Generation Complete!${NC}"
echo "New links generated: $NEW_COUNT"
echo "Already existed: $EXISTING_COUNT"
echo ""
echo "Files created:"
echo "  1. $OUTPUT_FILE (WhatsApp messages)"
echo "  2. $GENERATED_LINKS (tracking file)"
echo ""
echo "Next steps:"
echo "  1. Update WEBSITE_URL in this script"
echo "  2. Open $OUTPUT_FILE"
echo "  3. Click WhatsApp links to send invitations"
echo "===================================="
